name:                braindumper
version:             0.1.0.0
github:              "qualiaa/braindumper"
license:             BSD3
author:              "Jamie Bayne"
maintainer:          "jamiebayne@hotmail.com"
copyright:           "Jamie Bayne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/qualiaa/braindumper#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc > 2 && < 3
- pandoc-types
- doctemplates
- containers
- directory
- filepath
- data-default
- mtl
- text
- optparse-applicative
- extra

library:
  source-dirs: src

executables:
  braindumper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - braindumper

tests:
  braindumper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - braindumper
